export const CommerceCheckout = [
  {
    type: "function",
    stateMutability: "view",
    name: "MAX_FEE_BPS",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "feeRecipient",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "feeBps",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "paymentToken",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "totalEarningsByWallet",
    inputs: [{ name: "wallet", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "quoteSplit",
    inputs: [{ name: "baseAmount", type: "uint256" }],
    outputs: [
      { name: "grossAmount", type: "uint256" },
      { name: "feeAmount", type: "uint256" },
      { name: "merchantNetAmount", type: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "purchase",
    inputs: [
      { name: "productId", type: "string" },
      { name: "merchant", type: "address" },
      { name: "baseAmount", type: "uint256" },
    ],
    outputs: [
      { name: "grossAmount", type: "uint256" },
      { name: "feeAmount", type: "uint256" },
      { name: "merchantNetAmount", type: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "setFeeBps",
    inputs: [{ name: "newFeeBps", type: "uint16" }],
    outputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "setFeeRecipient",
    inputs: [{ name: "newRecipient", type: "address" }],
    outputs: [],
  },
] as const;
