export const EntitlementRegistry = [
  {
    type: "function",
    stateMutability: "view",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "forwarderAddress",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "onReport",
    inputs: [
      { name: "metadata", type: "bytes" },
      { name: "report", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "supportsInterface",
    inputs: [{ name: "interfaceId", type: "bytes4" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "hasEntitlement",
    inputs: [
      { name: "buyer", type: "address" },
      { name: "productId", type: "string" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "recordEntitlement",
    inputs: [
      { name: "buyer", type: "address" },
      { name: "productId", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "setStatus",
    inputs: [
      { name: "productId", type: "string" },
      { name: "newStatus", type: "uint8" },
    ],
    outputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "getStatus",
    inputs: [{ name: "productId", type: "string" }],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "setForwarderAddress",
    inputs: [{ name: "newForwarder", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "setExpectedAuthor",
    inputs: [{ name: "newExpectedAuthor", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "setExpectedWorkflowName",
    inputs: [{ name: "newExpectedWorkflowName", type: "bytes10" }],
    outputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "setExpectedWorkflowId",
    inputs: [{ name: "newExpectedWorkflowId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
  },
] as const;
